-- AI Voice-First Emergency Agent — PostgreSQL + PostGIS schema
-- GENERATED by scripts/generate_schema_sql.py from the SQLAlchemy models. Do not edit by hand;
-- change the models, then re-run the script. Requires PostgreSQL 14+ with PostGIS.

CREATE EXTENSION IF NOT EXISTS postgis;

-- departments
CREATE TABLE departments (
    key VARCHAR(50) NOT NULL, 
    name VARCHAR(255) NOT NULL, 
    facility_type VARCHAR(30), 
    dial_timeout_seconds INTEGER NOT NULL, 
    repeat_cycles INTEGER NOT NULL, 
    alert_webhook_url TEXT, 
    timezone VARCHAR(50) NOT NULL, 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_departments_dial_timeout CHECK (dial_timeout_seconds BETWEEN 5 AND 120), 
    CONSTRAINT ck_departments_repeat_cycles CHECK (repeat_cycles BETWEEN 1 AND 5), 
    UNIQUE (key)
);


-- facilities
CREATE TABLE facilities (
    type VARCHAR(30) NOT NULL, 
    name VARCHAR(255) NOT NULL, 
    address TEXT, 
    phone VARCHAR(40), 
    lat FLOAT NOT NULL, 
    lng FLOAT NOT NULL, 
    department_key VARCHAR(50), 
    capacity JSONB, 
    source VARCHAR(20) NOT NULL, 
    external_place_id VARCHAR(120), 
    last_synced_at TIMESTAMP WITH TIME ZONE, 
    is_synthetic BOOLEAN NOT NULL, 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_facilities_type CHECK (type IN ('hospital', 'fire_station', 'police_station', 'shelter', 'government_office', 'other')), 
    CONSTRAINT ck_facilities_source CHECK (source IN ('seed', 'overpass', 'google_places')), 
    CONSTRAINT uq_facilities_source_place UNIQUE (source, external_place_id)
);

CREATE INDEX ix_facilities_department_key ON facilities (department_key);
CREATE INDEX ix_facilities_type ON facilities (type);
CREATE INDEX ix_facilities_type_active ON facilities (type, is_active);

-- facility_lookups
CREATE TABLE facility_lookups (
    cache_key VARCHAR(64) NOT NULL, 
    provider VARCHAR(20) NOT NULL, 
    department_key VARCHAR(50) NOT NULL, 
    lat FLOAT NOT NULL, 
    lng FLOAT NOT NULL, 
    radius_km FLOAT NOT NULL, 
    result_count INTEGER, 
    response JSONB, 
    error TEXT, 
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT uq_facility_lookups_key UNIQUE (cache_key)
);

CREATE INDEX ix_facility_lookups_expires_at ON facility_lookups (expires_at);

-- incidents
CREATE TABLE incidents (
    incident_number INTEGER NOT NULL, 
    category VARCHAR(50) NOT NULL, 
    sub_type VARCHAR(100), 
    description TEXT, 
    address_text TEXT, 
    lat FLOAT, 
    lng FLOAT, 
    location_confidence FLOAT, 
    location_confirmed BOOLEAN NOT NULL, 
    people_affected INTEGER, 
    caller_phone VARCHAR(32), 
    severity INTEGER NOT NULL, 
    severity_level VARCHAR(20), 
    severity_explanation TEXT, 
    severity_signals JSONB, 
    severity_estimated BOOLEAN NOT NULL, 
    status VARCHAR(30) NOT NULL, 
    confidence VARCHAR(10), 
    confidence_reasons JSONB, 
    escalated BOOLEAN NOT NULL, 
    report_count INTEGER NOT NULL, 
    merged_into_id UUID, 
    source_call_id UUID, 
    embedding JSONB, 
    summary TEXT, 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_incidents_status CHECK (status IN ('open', 'dispatched', 'escalated', 'needs_review', 'resolved', 'closed', 'merged')), 
    CONSTRAINT ck_incidents_confidence CHECK (confidence IN ('high', 'medium', 'low')), 
    CONSTRAINT ck_incidents_severity_range CHECK (severity BETWEEN 0 AND 100), 
    CONSTRAINT ck_incidents_lat_range CHECK (lat IS NULL OR (lat BETWEEN -90 AND 90)), 
    CONSTRAINT ck_incidents_lng_range CHECK (lng IS NULL OR (lng BETWEEN -180 AND 180)), 
    FOREIGN KEY(merged_into_id) REFERENCES incidents (id) ON DELETE SET NULL
);

CREATE INDEX ix_incidents_category ON incidents (category);
CREATE INDEX ix_incidents_category_status ON incidents (category, status);
CREATE UNIQUE INDEX ix_incidents_incident_number ON incidents (incident_number);
CREATE INDEX ix_incidents_merged_into_id ON incidents (merged_into_id);
CREATE INDEX ix_incidents_source_call_id ON incidents (source_call_id);
CREATE INDEX ix_incidents_status ON incidents (status);
CREATE INDEX ix_incidents_status_created ON incidents (status, created_at);

-- calls
CREATE TABLE calls (
    call_sid VARCHAR(255) NOT NULL, 
    from_number VARCHAR(32), 
    status VARCHAR(50), 
    is_live BOOLEAN NOT NULL, 
    started_at TIMESTAMP WITH TIME ZONE, 
    ended_at TIMESTAMP WITH TIME ZONE, 
    duration_seconds INTEGER, 
    caller_language VARCHAR(50), 
    summary TEXT, 
    transferred_to_human BOOLEAN, 
    user_spoken BOOLEAN, 
    incident_id UUID, 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_calls_status CHECK (status IN ('in_progress', 'completed', 'transferred_to_human', 'caller_disconnect')), 
    FOREIGN KEY(incident_id) REFERENCES incidents (id) ON DELETE SET NULL
);

CREATE INDEX ix_calls_call_sid ON calls (call_sid);
CREATE INDEX ix_calls_incident_id ON calls (incident_id);
CREATE INDEX ix_calls_live_started ON calls (is_live, started_at);

-- department_contacts
CREATE TABLE department_contacts (
    department_id UUID NOT NULL, 
    name VARCHAR(255) NOT NULL, 
    role VARCHAR(20) NOT NULL, 
    phone VARCHAR(20) NOT NULL, 
    priority INTEGER NOT NULL, 
    zone VARCHAR(20), 
    duty_window JSONB, 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_department_contacts_role CHECK (role IN ('on_call', 'supervisor', 'director')), 
    CONSTRAINT uq_department_contacts_dept_priority UNIQUE (department_id, priority), 
    FOREIGN KEY(department_id) REFERENCES departments (id) ON DELETE CASCADE
);

CREATE INDEX ix_department_contacts_dept_active ON department_contacts (department_id, is_active);

-- escalations
CREATE TABLE escalations (
    incident_id UUID NOT NULL, 
    reason TEXT NOT NULL, 
    escalate_to JSONB NOT NULL, 
    source VARCHAR(30), 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(incident_id) REFERENCES incidents (id) ON DELETE CASCADE
);

CREATE INDEX ix_escalations_incident_id ON escalations (incident_id);

-- incident_events
CREATE TABLE incident_events (
    incident_id UUID NOT NULL, 
    event_type VARCHAR(60) NOT NULL, 
    actor VARCHAR(20) NOT NULL, 
    payload JSONB, 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_incident_events_actor CHECK (actor IN ('agent', 'system', 'human', 'watchdog')), 
    FOREIGN KEY(incident_id) REFERENCES incidents (id) ON DELETE CASCADE
);

CREATE INDEX ix_incident_events_incident_created ON incident_events (incident_id, created_at);

-- resources
CREATE TABLE resources (
    callsign VARCHAR(50) NOT NULL, 
    type VARCHAR(30) NOT NULL, 
    status VARCHAR(20) NOT NULL, 
    capabilities JSONB, 
    lat FLOAT NOT NULL, 
    lng FLOAT NOT NULL, 
    speed_kmh FLOAT, 
    queue_load INTEGER, 
    contact_number VARCHAR(32), 
    department_key VARCHAR(50), 
    home_facility_id UUID, 
    last_updated TIMESTAMP WITH TIME ZONE, 
    is_synthetic BOOLEAN NOT NULL, 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_resources_type CHECK (type IN ('ambulance', 'fire_truck', 'police_unit', 'rescue_team', 'flood_rescue_boat', 'hazmat_team', 'tow_truck', 'helicopter')), 
    CONSTRAINT ck_resources_status CHECK (status IN ('available', 'reserved', 'en_route', 'on_scene', 'busy', 'offline')), 
    CONSTRAINT ck_resources_coords CHECK (lat BETWEEN -90 AND 90 AND lng BETWEEN -180 AND 180), 
    UNIQUE (callsign), 
    FOREIGN KEY(home_facility_id) REFERENCES facilities (id) ON DELETE SET NULL
);

CREATE INDEX ix_resources_department_key ON resources (department_key);
CREATE INDEX ix_resources_status ON resources (status);
CREATE INDEX ix_resources_type ON resources (type);
CREATE INDEX ix_resources_type_status ON resources (type, status);

-- agent_tool_calls
CREATE TABLE agent_tool_calls (
    call_id UUID, 
    incident_id UUID, 
    tool_name VARCHAR(100) NOT NULL, 
    arguments JSONB, 
    result JSONB, 
    status VARCHAR(20), 
    duration_ms INTEGER, 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_agent_tool_calls_status CHECK (status IN ('success', 'error', 'rejected', 'not_found', 'none_available')), 
    FOREIGN KEY(call_id) REFERENCES calls (id), 
    FOREIGN KEY(incident_id) REFERENCES incidents (id)
);

CREATE INDEX ix_agent_tool_calls_call_id ON agent_tool_calls (call_id);
CREATE INDEX ix_agent_tool_calls_incident_id ON agent_tool_calls (incident_id);

-- assignments
CREATE TABLE assignments (
    incident_id UUID NOT NULL, 
    resource_id UUID NOT NULL, 
    status VARCHAR(30) NOT NULL, 
    eta_minutes FLOAT, 
    eta_at TIMESTAMP WITH TIME ZONE, 
    distance_km FLOAT, 
    score_breakdown JSONB, 
    reason TEXT, 
    approved_by VARCHAR(100), 
    delay_escalated_at TIMESTAMP WITH TIME ZONE, 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_assignments_status CHECK (status IN ('pending_approval', 'dispatched', 'en_route', 'arrived', 'rejected', 'cancelled', 'completed')), 
    FOREIGN KEY(incident_id) REFERENCES incidents (id) ON DELETE CASCADE, 
    FOREIGN KEY(resource_id) REFERENCES resources (id)
);

CREATE INDEX ix_assignments_incident_id ON assignments (incident_id);
CREATE INDEX ix_assignments_resource_id ON assignments (resource_id);
CREATE INDEX ix_assignments_status ON assignments (status);
CREATE INDEX ix_assignments_status_eta ON assignments (status, eta_at);

-- call_handoffs
CREATE TABLE call_handoffs (
    call_id UUID, 
    incident_id UUID, 
    department_id UUID, 
    call_sid VARCHAR(255) NOT NULL, 
    reason TEXT, 
    status VARCHAR(20) NOT NULL, 
    ladder JSONB, 
    total_steps INTEGER NOT NULL, 
    current_step INTEGER NOT NULL, 
    answered_contact_id UUID, 
    started_at TIMESTAMP WITH TIME ZONE, 
    ended_at TIMESTAMP WITH TIME ZONE, 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_call_handoffs_status CHECK (status IN ('pending', 'dialing', 'answered', 'exhausted', 'failed', 'simulated', 'cancelled')), 
    FOREIGN KEY(call_id) REFERENCES calls (id) ON DELETE SET NULL, 
    FOREIGN KEY(incident_id) REFERENCES incidents (id) ON DELETE SET NULL, 
    FOREIGN KEY(department_id) REFERENCES departments (id), 
    FOREIGN KEY(answered_contact_id) REFERENCES department_contacts (id)
);

CREATE INDEX ix_call_handoffs_call_id ON call_handoffs (call_id);
CREATE INDEX ix_call_handoffs_call_sid ON call_handoffs (call_sid);
CREATE INDEX ix_call_handoffs_incident_id ON call_handoffs (incident_id);

-- call_transcripts
CREATE TABLE call_transcripts (
    call_id UUID NOT NULL, 
    seq INTEGER NOT NULL, 
    role VARCHAR(20) NOT NULL, 
    content TEXT NOT NULL, 
    spoken_at TIMESTAMP WITH TIME ZONE, 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_call_transcripts_role CHECK (role IN ('caller', 'agent')), 
    FOREIGN KEY(call_id) REFERENCES calls (id)
);

CREATE INDEX ix_call_transcripts_call_id ON call_transcripts (call_id);
CREATE UNIQUE INDEX uq_call_transcripts_call_seq ON call_transcripts (call_id, seq);

-- incident_reports
CREATE TABLE incident_reports (
    incident_id UUID NOT NULL, 
    call_id UUID, 
    description TEXT, 
    people_affected INTEGER, 
    match_score FLOAT, 
    note VARCHAR(200), 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    FOREIGN KEY(incident_id) REFERENCES incidents (id) ON DELETE CASCADE, 
    FOREIGN KEY(call_id) REFERENCES calls (id)
);

CREATE INDEX ix_incident_reports_incident_id ON incident_reports (incident_id);

-- dispatch_notifications
CREATE TABLE dispatch_notifications (
    incident_id UUID NOT NULL, 
    assignment_id UUID, 
    resource_id UUID, 
    channel VARCHAR(30) NOT NULL, 
    recipient VARCHAR(255), 
    payload JSONB, 
    status VARCHAR(30), 
    error TEXT, 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_dispatch_notifications_channel CHECK (channel IN ('dashboard', 'sms', 'webhook')), 
    CONSTRAINT ck_dispatch_notifications_status CHECK (status IN ('sent', 'held_for_approval', 'failed', 'simulated')), 
    FOREIGN KEY(incident_id) REFERENCES incidents (id) ON DELETE CASCADE, 
    FOREIGN KEY(assignment_id) REFERENCES assignments (id), 
    FOREIGN KEY(resource_id) REFERENCES resources (id)
);

CREATE INDEX ix_dispatch_notifications_incident_id ON dispatch_notifications (incident_id);

-- escalation_attempts
CREATE TABLE escalation_attempts (
    handoff_id UUID NOT NULL, 
    contact_id UUID, 
    step_index INTEGER NOT NULL, 
    cycle INTEGER NOT NULL, 
    contact_name VARCHAR(255), 
    role VARCHAR(20), 
    phone VARCHAR(20) NOT NULL, 
    sms_status VARCHAR(20), 
    sms_sid VARCHAR(64), 
    dial_status VARCHAR(20) NOT NULL, 
    dial_call_sid VARCHAR(64), 
    answered BOOLEAN, 
    duration_seconds INTEGER, 
    started_at TIMESTAMP WITH TIME ZONE, 
    ended_at TIMESTAMP WITH TIME ZONE, 
    raw_status_events JSONB, 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_escalation_attempts_dial_status CHECK (dial_status IN ('pending', 'initiated', 'ringing', 'answered', 'completed', 'busy', 'no-answer', 'failed', 'canceled')), 
    CONSTRAINT uq_escalation_attempts_handoff_step UNIQUE (handoff_id, step_index), 
    FOREIGN KEY(handoff_id) REFERENCES call_handoffs (id) ON DELETE CASCADE, 
    FOREIGN KEY(contact_id) REFERENCES department_contacts (id)
);

CREATE INDEX ix_escalation_attempts_handoff_id ON escalation_attempts (handoff_id);

-- resource_location_pings
CREATE TABLE resource_location_pings (
    resource_id UUID NOT NULL, 
    assignment_id UUID, 
    lat FLOAT NOT NULL, 
    lng FLOAT NOT NULL, 
    speed_kmh FLOAT, 
    heading_deg FLOAT, 
    source VARCHAR(30), 
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL, 
    id UUID NOT NULL, 
    is_active BOOLEAN DEFAULT '1' NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
    PRIMARY KEY (id), 
    CONSTRAINT ck_pings_coords CHECK (lat BETWEEN -90 AND 90 AND lng BETWEEN -180 AND 180), 
    FOREIGN KEY(resource_id) REFERENCES resources (id) ON DELETE CASCADE, 
    FOREIGN KEY(assignment_id) REFERENCES assignments (id) ON DELETE SET NULL
);

CREATE INDEX ix_pings_resource_recorded ON resource_location_pings (resource_id, recorded_at);


-- ── PostGIS: nearest-unit search (app/services/resource_service.py) ───────────────────────────
-- resource_service builds the geography point on the fly from lat/lng and asks ST_DWithin; this
-- expression index makes that a spatial index scan instead of a full scan.
CREATE INDEX IF NOT EXISTS ix_resources_geog ON resources
    USING GIST ((ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography));
CREATE INDEX IF NOT EXISTS ix_facilities_geog ON facilities
    USING GIST ((ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography));
CREATE INDEX IF NOT EXISTS ix_incidents_geog ON incidents
    USING GIST ((ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography)) WHERE lat IS NOT NULL;

-- ── Concurrency: exactly one winner per unit (PDF §9) ──────────────────────────────────────────
-- resource_service.claim_resource runs, inside one transaction:
--   SELECT * FROM resources WHERE id = :id FOR UPDATE SKIP LOCKED;
--   UPDATE resources SET status = 'en_route' WHERE id = :id AND status = 'available';
