"""Generate the PostgreSQL + PostGIS DDL for the whole schema — no database needed.

    python scripts/generate_schema_sql.py            # writes db/schema.sql
    python scripts/generate_schema_sql.py --check    # exit 1 if db/schema.sql is out of date (CI-friendly)

The DDL is compiled by SQLAlchemy from the SAME models the app uses (so it can never drift from the code),
against the PostgreSQL dialect: JSONB, native UUID, CHECK constraints, FKs with ON DELETE, indexes. PostGIS
extras (extension + a GiST expression index on resources) are appended by hand below.

The file is reference/DBA documentation and a manual bootstrap option (`psql -f db/schema.sql`);
the app itself creates the schema through `scripts/init_db.py` or `alembic upgrade head`.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
os.environ.setdefault("DATABASE_URL", "sqlite:///./_schema_gen.db")  # never connected to

from sqlalchemy.dialects import postgresql  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

from app import models  # noqa: E402,F401
from app.core.database import Base  # noqa: E402

OUT = os.path.join(os.path.dirname(__file__), "..", "db", "schema.sql")

HEADER = """-- AI Voice-First Emergency Agent — PostgreSQL + PostGIS schema
-- GENERATED by scripts/generate_schema_sql.py from the SQLAlchemy models. Do not edit by hand;
-- change the models, then re-run the script. Requires PostgreSQL 14+ with PostGIS.

CREATE EXTENSION IF NOT EXISTS postgis;
"""

FOOTER = """
-- ── PostGIS: nearest-unit search (app/services/resource_service.py) ───────────────────────────
-- resource_service builds the geography point on the fly from lat/lng and asks ST_DWithin; this
-- expression index makes that a spatial index scan instead of a full scan.
CREATE INDEX IF NOT EXISTS ix_resources_geog ON resources
    USING GIST ((ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography));
CREATE INDEX IF NOT EXISTS ix_facilities_geog ON facilities
    USING GIST ((ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography));
CREATE INDEX IF NOT EXISTS ix_incidents_geog ON incidents
    USING GIST ((ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography)) WHERE lat IS NOT NULL;

-- ── Concurrency: exactly one winner per unit (PDF §9) ──────────────────────────────────────────
-- resource_service.claim_resource runs, inside one transaction:
--   SELECT * FROM resources WHERE id = :id FOR UPDATE SKIP LOCKED;
--   UPDATE resources SET status = 'en_route' WHERE id = :id AND status = 'available';
"""


def build() -> str:
    dialect = postgresql.dialect()
    parts = [HEADER]
    for table in Base.metadata.sorted_tables:
        parts.append(f"-- {table.name}" + (f": {table.comment}" if table.comment else ""))
        parts.append(str(CreateTable(table).compile(dialect=dialect)).strip() + ";\n")
        for index in sorted(table.indexes, key=lambda i: i.name or ""):
            parts.append(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
        parts.append("")
    parts.append(FOOTER)
    return "\n".join(parts).replace("\t", "    ")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    sql = build()
    path = os.path.abspath(OUT)
    if args.check:
        current = open(path).read() if os.path.exists(path) else ""
        if current != sql:
            print("db/schema.sql is out of date — run: python scripts/generate_schema_sql.py")
            return 1
        print("db/schema.sql is up to date")
        return 0
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(sql)
    print(f"wrote {path}: {len(Base.metadata.sorted_tables)} tables, {sql.count('CREATE INDEX')} indexes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
